[theme]

# Base colors can be 'light' or 'dark'
base = "light"

# Primary color for your app, specified as a hex or named CSS color
primaryColor = "#115e59"

# Background color for your app
backgroundColor = "#fafafa"

# Secondary background color for your app
secondaryBackgroundColor = "#f2f2f0"

# Text color for your app
textColor = "#042f2e"

# Font for your app, choose between "sans serif", "serif", and "monospace"
font = "sans serif"

baseRadius = "medium"

linkColor = "#64748b"

[deprecation]
showPyplotGlobalUse = false

[server]
enableStaticServing = false

[upload]
file_formats = ["csv", "xlsx"]
